initial commit
sandeepmehta2155/finalRepo-weeblyvids pull request #2
Opened 2021-05-06 10:07 UTC by sandeepmehta2155

2021-05-06 15:48 UTC, rohan9896 requested changes
Hey sandeep! I checked your code and I have to say that code is very clean and also you have re-used your components alot, that's why the lines of code is very less also

fixes - 
- side bar is not responsive
- You haven't added redirects file bcoz of which it is going to page not found on reload
- Pause button not working 

Some features you can add later - 
- Search functionality
-  separate 404 page
- Add a logo (maybe)

2021-05-06 15:48 UTC, rohan9896 commented on src/styles.css
> +  /* margin: 5rem; */
remove this comment

2021-05-07 07:41 UTC, kajol-rep approved these changes
Hi Sandeep,
reviewed your code, it looks clean.
I would like to suggest few things that will help you to make your UI better:
1. You can fix margin for your sidebar so that subscribers doesn't go to next line.
2. Make sure to keep UI clean, for this you can hide scrollbars if its not scrollable.
3. Make sure whenever the user clicks on thumbnail image or content it should go to video player page and it should be implemented on all the pages. As pages except home doesn't have this feature.

2021-05-07 16:20 UTC, sandeepmehta2155 commented
> Hey sandeep! I checked your code and I have to say that code is very clean and also you have re-used your components alot, that's why the lines of code is very less which is great
> 
> fixes -
> 
> * side bar is not responsive
> * You haven't added redirects file bcoz of which it is going to page not found on reload
> * Pause button not working
> 
> Some features you can add later -
> 
> * Search functionality
> * separate 404 page
> * Add a logo (maybe)

All issues have been resolved

2021-05-07 16:22 UTC, sandeepmehta2155 commented
> Hi Sandeep,
> reviewed your code, it looks clean.
> I would like to suggest few things that will help you to make your UI better:
> 
> 1. You can fix margin for your sidebar so that subscribers doesn't go to next line.
> 2. Make sure to keep UI clean, for this you can hide scrollbars if its not scrollable.
> 3. Make sure whenever the user clicks on thumbnail image or content it should go to video player page and it should be implemented on all the pages. As pages except home doesn't have this feature.

2021-05-09 05:48 UTC, sandeepmehta2155 commented
> Hi Sandeep,
> reviewed your code, it looks clean.
> I would like to suggest few things that will help you to make your UI better:
> 
> 1. You can fix margin for your sidebar so that subscribers doesn't go to next line.
> 2. Make sure to keep UI clean, for this you can hide scrollbars if its not scrollable.
> 3. Make sure whenever the user clicks on thumbnail image or content it should go to video player page and it should be implemented on all the pages. As pages except home doesn't have this feature.

Thanks Kajol for enhancing small pieces of UI resulting into a clean &  impressive app ,further acknowledge me for changes made or any changes required to be made.

2021-05-09 08:02 UTC, kajol-rep commented
> > Hi Sandeep,
> > reviewed your code, it looks clean.
> > I would like to suggest few things that will help you to make your UI better:
> > 
> > 1. You can fix margin for your sidebar so that subscribers doesn't go to next line.
> > 2. Make sure to keep UI clean, for this you can hide scrollbars if its not scrollable.
> > 3. Make sure whenever the user clicks on thumbnail image or content it should go to video player page and it should be implemented on all the pages. As pages except home doesn't have this feature.
> 
> Thanks Kajol for enhancing small pieces of UI resulting into a clean & impressive app ,further acknowledge me for changes made or any changes required to be made.

Thanks for considering my suggestions. Surely will acknowledge you further for any changes.

2021-05-09 14:00 UTC, rohan9896 approved these changes
Well done sandeep😃

2021-05-10 13:02 UTC, merged